[WIP] Level feature permissions
Refty/lemverse pull request #19
Opened 2022-09-13 16:18 UTC by alimtunc

Adding possibility to disable or restrict feature to admin in level editor

Implemented for shout and kick, missing for notifications

<img width="861" alt="Screenshot 2022-09-13 at 18 16 57" src="https://user-images.githubusercontent.com/18298759/189953788-acb541ad-1285-4a17-a2f7-fb4f630d4203.png">

2022-09-15 20:15 UTC, ramnes requested changes
A few things to change I think.

Other problems I've found while testing:
* Shout is always disabled, whatever the settings option
* Other settings options (name, visibility and spawn position) are broken: "Match failed"

2022-09-15 20:15 UTC, ramnes commented on core/lib/misc.js
> +const canUseLevelFeature = (user, featureName, showNotification = true) => {
`showNotification` doesn't seem used :)

```suggestion
const canUseLevelFeature = (user, featureName) => {
```

2022-09-15 20:15 UTC, ramnes commented on core/lib/misc.js
> +    if (showNotification && user.roles?.admin) lp.notif.error(`This feature is disabled: ${featureName}`);
```suggestion
    if (user.roles?.admin) lp.notif.error(`This feature is disabled: ${featureName}`);
```

2022-09-15 20:15 UTC, ramnes commented on core/modules/console/client/console.hbs.html
> +      <input disabled="{{chatDisabled}}" type="file" tabindex="1" name="file" id="console-file" class="console-file" accept="image/png, image/jpeg, image/gif" />
We probably should put the whole `<div class=console>` into a condition. The disabled input text and buttons are not very user-friendly.

2022-09-15 20:15 UTC, ramnes commented on core/client/ui/toolboxes/level-toolbox.js
> +      { value: 'default', label: 'Default' },
```suggestion
      { value: 'enabled', label: 'Enabled' },
```

2022-09-15 20:15 UTC, ramnes commented on core/server/levels.js
> +    check(featuresPermissions, Object);
We probably want to do something like this, at least:

```suggestion
    check(featuresPermissions, { shout: String, globalChat: String, punch: String });
```

Ideally we'd want to check against the possible dropdown values.

2022-09-15 20:15 UTC, ramnes commented on core/client/ui/toolboxes/level-toolbox.js
> +    const level = currentLevel(Meteor.user());
Let's avoid these two lines on each handler by not passing the whole `featuresPermissions` object to `updateLevel`, but just the value that changed.

2022-09-15 20:15 UTC, ramnes commented on core/client/ui/toolboxes/level-toolbox.scss
> +  .feature-dropdown {
Let's make it a bit larger:

![Screenshot from 2022-09-15 20-12-50](https://user-images.githubusercontent.com/835072/190499717-19b59fee-21de-41d5-8d24-6f8542b12cb6.png)

2022-09-16 09:18 UTC, alimtunc commented on core/modules/console/client/console.hbs.html
> +      <input disabled="{{chatDisabled}}" type="file" tabindex="1" name="file" id="console-file" class="console-file" accept="image/png, image/jpeg, image/gif" />
I don't think it's more user friendly to completely disable the chat ? That's weird to just see some messages
<img width="1101" alt="Capture d’écran 2022-09-16 à 11 17 36" src="https://user-images.githubusercontent.com/18298759/190603347-c231de9d-c5d5-4751-816b-3383284e60a4.png">

2022-09-16 09:23 UTC, alimtunc commented on core/lib/misc.js
> +const canUseLevelFeature = (user, featureName, showNotification = true) => {
It was used for globalChat to not showing it since we have a message error in console, we can show it as notification too.

2022-09-16 12:53 UTC, ramnes commented on core/modules/console/client/console.hbs.html
> +      <input disabled="{{chatDisabled}}" type="file" tabindex="1" name="file" id="console-file" class="console-file" accept="image/png, image/jpeg, image/gif" />
I think it's fine but if you don't like it, let's put back the bottom but without the "Send" button and with more grey then :)

2022-09-16 13:43 UTC, alimtunc commented on core/modules/console/client/console.hbs.html
> +      <input disabled="{{chatDisabled}}" type="file" tabindex="1" name="file" id="console-file" class="console-file" accept="image/png, image/jpeg, image/gif" />
What about this ?

<img width="863" alt="Capture d’écran 2022-09-16 à 15 43 22" src="https://user-images.githubusercontent.com/18298759/190653144-20da9ec4-e468-48d7-8945-4efac2c81803.png">

2022-09-22 19:02 UTC, ramnes approved these changes

2022-09-22 19:03 UTC, ramnes commented
@xsyann needs to be merged in the freeze branch

2022-09-22 19:03 UTC, merged